spring:
  profiles:
    active: dev
  thymeleaf:
    check-template-location: false
  task:
    scheduling:
      pool:
        size: 8

  application:
    name: konijntje
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8090